server: ## PORT
  port: 8080
  error:
    whitelabel:
      enabled: true
    include-exception: false
    include-message: never
    include-stacktrace: never

spring:
  profiles: ##PROFILES
    active: local,production
  jpa:  ## HIBERNATE
    hibernate:
      use-new-id-generator-mappings: true
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    repositories:
      enabled: true
    open-in-view: true
  output: ##CMDLN
    ansi:
      enabled: always
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher
#  web:
#    resources:
#      add-mappings: false
#hibernate:
#  dialect: org.hibernate.dialect.MySQL5InnoDBDialect

CONSTANTS:
  PROJECTNAME: "SPRING_BASE"
  APIPATHS: "user,"
  SALTVALUE: "salt"
  ACCESSTOKENNAME: "ac"
  REFRESHTOKENNAME: "rf"
  REFRESHSALTVALUE: "salt"
  LOCKDOWNTIME: "30"

